# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
  commands:
    - pip install -r neopdf_capi/docs/requirements.txt
    - cd neopdf_capi/docs && make html
    - mkdir -p _readthedocs/html
    - cp -r neopdf_capi/docs/build/html/* _readthedocs/html/

python:
  install:
    - requirements: neopdf_capi/docs/requirements.txt
