site_name: NeoPDF
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/neopdf.svg
  favicon: assets/neopdf.svg
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
extra_css:
  - custom.css
  - assets/stylesheets/notebooks.css
  - https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Installation: installation.md
  - Development with Pixi: development-with-pixi.md
  - Features: design-and-features.md
  - Design Rationale: design.md
  - Custom Interpolation: custom-interpolation.md
  - CLI Tutorials: cli-tutorials.md
  - TMDlib Interface: tmdlib.md
  - Examples:
      - '<i class="devicon-python-plain colored"></i> Python API': 'examples/neopdf-pyapi.ipynb'
      - '<i class="devicon-cplusplus-plain colored"></i> C++ OOP API': 'examples/c-oop.md'
      - '<i class="devicon-c-plain colored"></i> C/C++ API': 'examples/c.md'
      - '<i class="devicon-fortran-original colored"></i> Fortran API': 'examples/fortran.md'
      - '<img src="https://cdn.simpleicons.org/wolfram/c83737" alt="Wolfram" style="height: 1em; vertical-align: -0.125em; margin-right: 0.25em;"/> Mathematica': 'examples/mathematica.md'
plugins:
  - search
  - mermaid2
  - mkdocs-jupyter:
      execute: false
      include_source: true
      theme: dark
      include: ["*.ipynb", "*.nb.py"]
      execute_ignore: []
      allow_errors: false
      kernel_name: python3
      ignore_h1_titles: true
      show_input: true
      no_input: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
