site_name: NeoPDF
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
extra_css:
  - custom.css
  - assets/stylesheets/notebooks.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Installation: installation.md
  - Features: design-and-features.md
  - Design: design.md
  - CLI Tutorials: cli-tutorials.md
  - Examples:
      - 'Python API': 'examples/neopdf-pyapi.ipynb'
      - 'C++ OOP API': 'examples/c-oop.md'
      - 'C API': 'examples/c.md'
      - 'Fortran API': 'examples/fortran.md'
plugins:
  - search
  - mermaid2
  - mkdocs-jupyter:
      execute: false
      include_source: true
      theme: dark
      include: ["*.ipynb", "*.nb.py"]
      execute_ignore: []
      allow_errors: false
      kernel_name: python3
      ignore_h1_titles: true
      show_input: true
      no_input: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
