name: Run benchmarks

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run criterion benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Get data
        uses: ./.github/actions/cache-data

      - name: Cache Criterion results
        uses: actions/cache@v4
        with:
          path: target/criterion
          key: ${{ runner.os }}-criterion-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-criterion-main
            ${{ runner.os }}-criterion-

      - name: Run benchmarks
        run: |
          export NEOPDF_DATA_PATH=${PWD}/neopdf-data
          cargo bench -p  neopdf@0.3.0-alpha4

      - name: Upload benchmark reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: criterion-reports-${{ github.sha }}
          path: target/criterion/report/
