name: Check MSRV

on: [push]

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run check
        run: |
          # extract the MSRV from Root `Cargo.toml`
          MSRV=$(grep '^rust-version ' Cargo.toml | cut -d= -f2- | tr -d ' "')
          rustup default "${MSRV}"
          cargo check --all-targets
