name: Deploy MkDocs to GitHub Pages

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies 📦
        run: pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages 🚀
        run: |
          cd docs
          mkdocs build
          mkdocs gh-deploy --force
