name: Build NeoPDF Container

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free disk space
        run: |
          # inspired by: https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
          df -h
          # 100 largest packages, in ascending order
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          sudo apt-get remove -y google-cloud-cli
          sudo apt-get remove -y azure-cli
          sudo apt-get remove -y microsoft-edge-stable
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^temurin-.*-jdk'
          sudo apt-get remove -y google-chrome-stable
          sudo apt-get remove -y '^llvm-.*-dev'
          sudo apt-get remove -y firefox
          sudo apt-get remove -y powershell
          sudo apt-get remove -y mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          # disk space after removing packages
          df -h
      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: neopdf-container
          containerfiles: maintainer/neopdf-container/Containerfile
          context: maintainer/neopdf-container/
          oci: true
      - name: Publish image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: neopdf-container
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
