name: Build NeoPDF Container

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        run: |
          # inspired by: https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
          df -h
          # 100 largest packages, in ascending order
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          sudo apt-get remove -y google-cloud-cli
          sudo apt-get remove -y azure-cli
          sudo apt-get remove -y microsoft-edge-stable
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^temurin-.*-jdk'
          sudo apt-get remove -y google-chrome-stable
          sudo apt-get remove -y '^llvm-.*-dev'
          sudo apt-get remove -y firefox
          sudo apt-get remove -y powershell
          sudo apt-get remove -y mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          # disk space after removing packages
          df -h

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/neopdf-container
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: maintainer/neopdf-container/
          file: maintainer/neopdf-container/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
