name: Run the Rust tests 🦀

on:
  push:
    branches-ignore:
      - add-container

env:
  CARGO_TERM_COLOR: always
  NEOPDF_DATA_PATH: ${{ github.workspace }}/neopdf-data

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Get data
        uses: ./.github/actions/cache-data

      - name: Run tests 🦀
        env:
          RUSTFLAGS: '-Cinstrument-coverage -Clink-dead-code'
        run: |
          export NEOPDF_DATA_PATH=${PWD}/neopdf-data
          # Run tests without doctests to avoid coverage instrumentation issues
          cargo test --lib --bins --tests --no-fail-fast 2> >(tee stderr 1>&2)
          # from https://stackoverflow.com/a/51141872/812178
          sed -i 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' stderr

      - name: Generate code coverage
        run: |
          # from https://github.com/NNPDF/pineappl/blob/master/.github/workflows/rust.yml
          find . -name '*.profraw' -exec $(rustc --print target-libdir)/../bin/llvm-profdata merge -sparse -o neopdf.profdata {} +
          ( sed -nE 's/[[:space:]]+Running( unittests|) [^[:space:]]+ \(([^)]+)\)/\2/p' stderr ) | \
              xargs printf ' --object %s' | \
              xargs $(rustc --print target-libdir)/../bin/llvm-cov export \
                  --ignore-filename-regex=index.crates.io \
                  --ignore-filename-regex=rustc \
                  --ignore-filename-regex=neopdf/tests \
                  --ignore-filename-regex=neopdf_capi \
                  --ignore-filename-regex=neopdf_cli/tests \
                  --instr-profile=neopdf.profdata \
                  --skip-functions \
                  --object target/debug/neopdf \
                  --format lcov > lcov.info
          grep SF lcov.info | sort -u | sed 's/SF://'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rust
